alias vimrc='lvim ~/.vimrc'
alias nvimconfig='lvim ~/.config/nvim/init.lua'
alias bashrc='lvim ~/.bashrc && source ~/.bashrc'
alias bashalias='lvim ~/.bash_aliases && source ~/.bash_aliases'
alias sourcebash='source ~/.bashrc'
alias grep='grep --color'
alias cp='cp -v'
alias ls='ls --color'
alias mkdir='mkdir -pv'
alias goprojects='cd ~/wd/go'
alias gosrc='cd ~/wd/go/src'
alias gobin='cd ~/wd/go/bin'
alias cppsrc='cd ~/wd/c++'
alias csrc='cd ~/wd/c'
alias csharpsrc='cd ~/wd/csharp'
alias pythonsrc='cd ~/wd/python'
alias phpsrc='cd ~/wd/php'
alias jssrc='cd ~/wd/js'
alias javasrc='cd ~/wd/java'
alias pokemonrandomizer='cd ~/pokemon/randomizer'
alias dotfiles='cd ~/dotfiles'
alias lg='lazygit'
alias lv='lvim'

#alias to install the last version of lunarvim (nightlybuild on master)
alias installLunarVim='bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)'
